import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { GeneratorInput } from "./schema";

/**
 * Entry point for all generation logic.
 * Currently a stub — each layer will be implemented in its own module.
 */
export async function generate(input: GeneratorInput, outDir: string): Promise<void> {
  const layer = parseInt(input.layer);

  console.log(`Generating Layer ${layer} config for ${input.hardware} → ${outDir}`);

  await mkdir(outDir, { recursive: true });

  // TODO: implement layer generators
  // Layer 0: generateLan(input, outDir)
  // Layer 1: generateWan(input, outDir)
  // Layer 2: generateDomain(input, outDir)
  // Layer 3: generateServices(input, outDir)

  const summary = [
    `# Generated HomeLab config`,
    ``,
    `- Hardware: ${input.hardware}`,
    `- Layer: ${layer}`,
    `- Server IP: ${input.serverIp}`,
    `- Timezone: ${input.timezone}`,
    ...(input.domain ? [`- Domain: ${input.domain}`] : []),
    ``,
    `Generated by \`homelab generate\`. See generator/ for implementation.`,
  ].join("\n");

  await writeFile(join(outDir, "README.md"), summary + "\n");

  console.log(`Done. Output in ${outDir}/`);
}
